### ISSUE TITLE
[출석] 02.18 수정사항

### ISSUE THREAD

**Issue by Jeonilju** [Jeonilju/RenewSecsm#29]
[출석]
	출석 데이터가 없는경우 출력이 안되는 버그 수정
	출석 데이터는 지금 이전 Secsm팀 PL님께 연락해서 코드 인수인계중입니다.

**Comment by ChoKyuhyeon** [comment]
이거 예전에 수정했는데 푸쉬할때 계속 에러남 ㅠㅠㅠ
