### ISSUE TITLE
px에 필요한 자잘한 기능들 추가

### ISSUE THREAD

**Issue by Jeonilju** [Jeonilju/RenewSecsm#6]
1. 물품 구매시 구매확인을 모달에 출력되도록
       + 출력된것을 통해 환불도 가능하도록 처리

2. 물품 구매시 동적으로 잔액 확인

3. 구매 내역 페이징

4. 구매 내역에서 환불기능

5. 상품 요청 디자인 변경

6. 상품추가를 좀더 쉽게 + 디자인 변경

**Comment by choseungyoon** [comment]
2 동적으로 잔액환인
4. 구매내역 환불기능
완료
